### PR TITLE
fix: load failure when reloading a previous project

### LINKED ISSUE #282: [Bug]: Loading a project twice can trigger a "split()" error message.
### What happened?

Steps to reproduce:

- close all projects
- create a blank project
- load a project from a file
- close that loaded project
- load the same project again from a file

Triggers an error message "Failed to load project: ...."

You can't tell what the error was, because that toast is trying to read the `fsPath` which is `undefined` producing a `Cannot read properties of undefined` but if you fix that error, then the error message is `XXX shares the same ID (###) and is already open.`

## Work around solution to bug

- close all projects
- exit Rivet
- start Rivet
- load that project from a file

Loading works if state is clean.

### What was the expected functionality?

Rivet should be able to load projects from a file if there is no tab visible saying it's already loaded.

### Describe your environment

Windows, Node 20.10.0,

### Relevant log output

_No response_

### Relevant screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by codemile**
This PR closes #282 

## Steps to reproduce bug

- have multiple projects open
- select a project tab
- close that project tab
- reopen that project from file

## Reason

The act of "closing the currently selected tab" caused a bug where the "currentProject" is removed from Recoil, but then in a `useEffect()` that closed project would get added back to "openProjects". It was a simple logic problem on trying to remember the previous project.

> Note: this PR also replaces "effects_UNSTABLE" with "effects" as it's now a stable feature of Recoil

### CODE REVIEW

File: packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts [hunk 1]
```diff
@@ -76,26 +77,26 @@ export function useSyncCurrentStateIntoOpenedProjects() {
...
         openedGraph: currentGraph.metadata!.id!,
-      });
+      } satisfies OpenedProjectInfo);
     }
   }, [currentGraph, currentProject, prevProjectState.project.metadata.id]);
 
   // Sync current graph into opened projects when user switches projects.
   useEffect(() => {
-    if (prevProjectState.project != null && prevProjectState.project.metadata.id !== currentProject.metadata.id) {
+    if (prevProjectState.project != null && prevProjectState.project.metadata.id !== currentProject.metadata.id && openedProjects[prevProjectState.project.metadata.id]) {
```
Comment (codemile) [inline packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts:86]: this is the FIX here, don't add "prevProjectState" if it's no longer in "openedProjects"

**Comment by abrenneke** [comment]
> Note: this PR also replaces "effects_UNSTABLE" with "effects" as it's now a stable feature of Recoil

cool!

File: packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts [hunk 2]
```diff
@@ -1,7 +1,8 @@
+import { type Project } from '@ironclad/rivet-core';
 import { useEffect, useState } from 'react';
 import { useRecoilState, useRecoilValue } from 'recoil';
 import {
-  loadedProjectState,
+  loadedProjectState, type OpenedProjectInfo,
```
Comment (abrenneke) [inline packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts:5]: prettier?

File: packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts (hunk 1 above)
Comment (abrenneke) [reply packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts:86]: Thanks!

File: packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts [hunk 3]
```diff
@@ -24,7 +25,7 @@ export function useSyncCurrentStateIntoOpenedProjects() {
         [currentProject.metadata.id]: {
           project: currentProject,
           fsPath: null,
-        },
+        } satisfies OpenedProjectInfo,
```
Comment (abrenneke) [inline packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts:28]: Doesn't this already take an `OpenedProjectInfo`? How come we need all the `satisfies` now, shouldn't it already check that the value is valid? Granted this rings a bell of weird TS behavior I was running in to...

File: packages/app/src/state/savedGraphs.ts [hunk 4]
```diff
@@ -135,7 +135,7 @@ export const projectPluginsState = selector({
 
 export type OpenedProjectInfo = {
   project: Project;
-  fsPath: string;
+  fsPath?: string | null;
```
Comment (abrenneke) [inline packages/app/src/state/savedGraphs.ts:138]: Does this need to be `string | null | undefined`? Can we choose either `null` or `undefined`?

File: packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts (hunk 3 above)
Comment (codemile) [reply packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts:28]: It's actually an atom setter function, which is a callback function but the TypeScript type declarations of the setter is pretty complex. As a result, my IDE (WebStorm) was not matching usages of `OpenedProjectInfo` to this code.

So I'm not trying to enforce type here, I'm trying to fix if you "CTRL+CLICK" to find usages of `OpenedProjectInfo`. Without the `satisfies` it was hard to find where `fsPath` was being used.

I can remove these if you want, but leaving them will help with managing the code.

Yeah, I know this is a bit of pain, but I do this on my own projects to improve static typing and I can navigate around the code better and update it quicker. You only need to add them when you have things like union types which confuses IDEs.

Here is a quick example:

```
interface Cat {name: string};
interface Dog {name: string};

type Animal = Cat | Dog;

const x: Animal = {name: "example"};
```

If you try to find usages of `Cat.name` the IDE will show zero usages. The same for the `Dog.name`, because technically `x` is both and neither at the same time. (I haven't tested this example, but on larger complex types it happens).

Meanwhile, this will fix that.

```
const x: Animal = {name: "example"} satisfies Cat;
```

This is happening a lot in our code base. Making it a bit hard for me to figure out the impact of changing code.

File: packages/app/src/state/savedGraphs.ts (hunk 4 above)
Comment (codemile) [reply packages/app/src/state/savedGraphs.ts:138]: The code does use `null` in some spots.

```
      setOpenedProjects((openedProjects) => ({
        ...openedProjects,
        [currentProject.metadata.id]: {
          project: currentProject,
          fsPath: null,
        } satisfies OpenedProjectInfo,
      }));
```

On the subject of `nulls` in the code. There are several places where things like `x == null` or `x != null` are being used. These expressions are leveraging type coercion, and can be pretty confusing for junior developers. For example; `x == null` will be `true` if `x` is `undefined`. That can introduce bugs if the dev isn't aware of what's going on.

I would like to later, clean these up and make the expressions more explicit and not rely on coercion. In the meantime, I think it's best we document with the types that `null` and `undefined` are being used interchangeably in the code.

File: packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts (hunk 2 above)
Comment (codemile) [reply packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts:5]: fixed.

I would like to get this issue done, and make lint/pretty part of the PR review process. I've seen people setup PRs so that comments for lint problems are auto added. That way we can automate these sorts of things.

Also, the entire code base could use a pretty pass because if I run it on the code now it generates a lot of changed files. We need to do a PR to clean it up and get it merged so we can stabilize the main branch.

File: packages/app/src/state/savedGraphs.ts (hunk 4 above)
Comment (abrenneke) [reply packages/app/src/state/savedGraphs.ts:138]: @codemile It's an idiom we use at ironclad, `== null` and `!= null` are explicitly allowed, even though `null` isn't really. There's even an [estlint rule config](https://eslint.org/docs/latest/rules/eqeqeq#allow-null) for it. The idea it to treat `null` and `undefined` as basically the same thing, but so that you don't have to do `val === null || val === undefined` all over the places. This follows the same logic as `??`, which checks for null or undefined.

File: packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts (hunk 2 above)
Comment (abrenneke) [reply packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts]: Ah, yeah, it's a prettier version difference problem. My editor is configured to run for Ironclad's prettier version which is a little behind. I'd love to have CI do that stuff too @codemile

File: packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts (hunk 3 above)
Comment (abrenneke) [reply packages/app/src/hooks/useSyncCurrentStateIntoOpenedProjects.ts:28]: Interesting idea, I can see how that's useful!

**Review by abrenneke — APPROVED** [review]
LGTM! :ship:
