### PR TITLE
fix: hotkeys on Windows by adding a custom hook

### LINKED ISSUE #261: [Bug]: Global hot keys on Windows do not work
### What happened?

Hot keys such as "Ctrl+S" don't work on Windows. Investigated the issue down to Tauri, and looked at the Rust code in `main.rs` where the top menu is configured. Can confirm that hot keys are working on Mac as expected.

Found this relevant open issue on Tauri that hotkey support is known to be broken on Windows.

https://github.com/tauri-apps/wry/issues/451

Issue has been open since 2021, I don't think a fix is coming soon.

There aren't a lot of global hot keys being used. A possible work around would be a DOM listener just for Windows that mimics menu triggers.

### What was the expected functionality?

Pressing "Ctrl + S" should save the project.

### Describe your environment

Windows 11, Node 20.4.0

### Relevant log output

_No response_

### Relevant screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by codemile**
Adds a hook that applies an onKeyUp listener to `window` and triggers menu actions.

Only applies the hook when the userAgent is `Win64`.

Resolves #261

### CODE REVIEW

File: packages/app/src/hooks/useWindowsHotfix.tsx [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+interface HotfixWindow extends Window {
+    __tauri_hotfix?: boolean;
+}
+declare let window: HotfixWindow;
+
+const isWindowsPlatform = typeof navigator !== 'undefined' && navigator.userAgent.includes('Win64');
+
+if(isWindowsPlatform) {
+    console.warn('Hotfix applied for Windows platform');
+}
```
Comment (abrenneke) [inline packages/app/src/hooks/useWindowsHotfix.tsx:13]: Do you mind running prettier on this file?

File: packages/app/src/hooks/useWindowsHotfix.tsx [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+
+/**
+ * Applies a keyboard shortcut hotfix for Windows platform.
+ */
+export const useWindowsHotfix = () => {
```
Comment (abrenneke) [inline packages/app/src/hooks/useWindowsHotfix.tsx:18]: How about `useWindowsHotkeysFix`?

File: packages/app/src/hooks/useWindowsHotfix.tsx [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+    const runMenuCommandImpl = useRunMenuCommand();
+
+    // @see https://github.com/Ironclad/rivet/issues/261
+    useEffect(() => {
+        if (typeof window === 'undefined' || !isWindowsPlatform || window.__tauri_hotfix) {
```
Comment (abrenneke) [inline packages/app/src/hooks/useWindowsHotfix.tsx:23]: A hotfix is more like "fixing something that's currently running (i.e. hot)", that's why I was saying "hotkey fix"

File: packages/app/src/hooks/useWindowsHotfix.tsx [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+            return;
+        }
+
+        const onKeyUp = ({ key, ctrlKey, shiftKey }: KeyboardEvent) => {
+            const code = `${ctrlKey ? 'CmdOrCtrl+' : ''}${shiftKey ? 'Shift+' : ''}${key.toUpperCase()}`;
```
Comment (abrenneke) [inline packages/app/src/hooks/useWindowsHotfix.tsx:28]: Clever way of doing this, nice

**Review by abrenneke — CHANGES_REQUESTED** [review]
Just a couple small things, otherwise looks good!

**Comment by codemile** [comment]
thanks, I'll push changes later today.

File: packages/app/src/hooks/useWindowsHotfix.tsx (hunk 1 above)
Comment (codemile) [reply packages/app/src/hooks/useWindowsHotfix.tsx]: Yeah, we should add prettier to eslint so that it's part of the linting pass. That way we can fail PRs if the code isn't formatted correctly.

File: packages/app/src/hooks/useWindowsHotfix.tsx (hunk 3 above)
Comment (codemile) [reply packages/app/src/hooks/useWindowsHotfix.tsx]: agreed, not a great name. lol

File: packages/app/src/hooks/useWindowsHotfix.tsx (hunk 4 above)
Comment (codemile) [reply packages/app/src/hooks/useWindowsHotfix.tsx]: thank copilot, lol

**Comment by codemile** [comment]
Done, thanks for the feedback.

File: packages/app/src/hooks/useWindowsHotfix.tsx (hunk 1 above)
Comment (abrenneke) [reply packages/app/src/hooks/useWindowsHotfix.tsx]: Definitely

**Review by abrenneke — APPROVED** [review]
Looks awesome thank you!
