### PR TITLE
fix: input/output names on CodeNode can crash render

### LINKED ISSUE #263: [Bug]: adding a CodeNode with empty inputs/outputs crashes the render function
### What happened?

When working with the `CodeNode` adding an input without a name triggers a cascade of console errors that can crash the main render. Deleting the node can fix the issue or giving the input a name.

### What was the expected functionality?

Unnamed inputs/outputs should not cause any errors and be handled accordingly.

### Describe your environment

MacOS, Node 14.0.0, etc.

### Relevant log output

```shell
react-dom.development.js:86  Warning: Encountered two children with the same key, `input-`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at div
    at NodePorts (http://localhost:5173/src/components/NodePorts.tsx:47:3)
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=848ac60d:18:5)
    at NodePortsRenderer (http://localhost:5173/src/components/NodePorts.tsx:25:6)
    at http://localhost:5173/src/components/VisualNode.tsx:284:3
    at div
    at http://localhost:5173/src/components/VisualNode.tsx:39:3
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=848ac60d:18:5)
    at DraggableNode (http://localhost:5173/src/components/DraggableNode.tsx:23:3)
    at div
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-6UQ5HDQG.js?v=848ac60d:1512:49
    at DndContext2 (http://localhost:5173/node_modules/.vite/deps/chunk-632M7M3Z.js?v=848ac60d:2737:5)
    at NodeCanvas (http://localhost:5173/src/components/NodeCanvas.tsx:137:3)
    at ErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=848ac60d:18:5)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-6UQ5HDQG.js?v=848ac60d:1512:49
    at GraphBuilder (http://localhost:5173/src/components/GraphBuilder.tsx:65:29)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-6UQ5HDQG.js?v=848ac60d:1512:49
    at RivetApp (http://localhost:5173/src/components/RivetApp.tsx:63:7)
    at QueryClientProvider (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-query.js?v=848ac60d:2518:3)
    at RecoilRoot_INTERNAL (http://localhost:5173/node_modules/.vite/deps/recoil.js?v=848ac60d:2818:3)
    at RecoilRoot (http://localhost:5173/node_modules/.vite/deps/recoil.js?v=848ac60d:2936:5)

react-dom.development.js:27292  Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:27292:11)
    at scheduleUpdateOnFiber (react-dom.development.js:25475:3)
    at dispatchSetState (react-dom.development.js:17527:7)
    at useNodePortPositions.ts:122:7
    at useNodePortPositions.ts:127:5
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)
    at commitLayoutEffects_begin (react-dom.development.js:24674:7)
    at commitLayoutEffects (react-dom.development.js:24612:3)
```

### Relevant screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by codemile**
Fixes #263 by ensuring the input/output names used by `CodeNode` are valid.

- rewrite non-alphanumeric letters as "_" underscore
- removes duplicate inputs/outputs which caused errors
- removes empty inputs/outputs from list

> Note, item 1 could be a breaking change for anyone using input names like "bad$xamp!es" as it gets rewritten to "bad_xamp_es". I made this change without discussing, but can be reverted if needed.

### CODE REVIEW

File: packages/core/src/model/nodes/CodeNode.ts [hunk 1]
```diff
@@ -15,6 +15,9 @@ import { nodeDefinition } from '../NodeDefinition.js';
 
 export type CodeNode = ChartNode<'code', CodeNodeData>;
 
+const maskInput = (name: string) => name.trim().replace(/[^a-zA-Z0-9_]/g, '_');
```
Comment (abrenneke) [inline packages/core/src/model/nodes/CodeNode.ts:18]: well technically `$` is valid in an identifier too, but it looks like valid identifiers are... [complicated](https://stackoverflow.com/a/9337047)

**Review by abrenneke — APPROVED** [review]
Looks good to me, most people are probably just using camel case or underscore case so we don't have to worry about backwards compatibility

File: packages/core/src/model/nodes/CodeNode.ts (hunk 1 above)
Comment (codemile) [reply packages/core/src/model/nodes/CodeNode.ts:18]: I see this more as asking if Rivet should have validation rules for the name of inputs/outputs on nodes. As it is now, it's just a `stringList` type and you can put anything. That could be a headache later for someone, for example, making a plugin but doesn't realized "#$(#@" is a valid input name and it crashes their plugin.

My recommendation, is to introduce a new type as example "inputList" which includes validation rules. (i.e. a blank string is not a valid input name). In this way, maybe we can add an input list editor that would highlight that input as invalid, and again highlight it if the user enters an invalid name.

I say this, because I think there are other nodes with the same problem. Like the passthrough node might be an example. Anywhere, that the user can add/remove inputs/outputs manually is subject to these kinds of issues.

Comment (abrenneke) [reply packages/core/src/model/nodes/CodeNode.ts:18]: That would be great,
